version: '3.2'
services:
  go_sample:
    container_name: $CONTAINER_NAME
    # ホスト名を明示的に指定する
    hostname: localhost
    # ゾンビプロセス防止
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
      args:
        USER_ID: 1000
        USER_NAME: $USER_NAME
        GROUP_ID: 1000
        GROUP_NAME: $USER_NAME
        WORK_DIR: $WORK_DIR
        GO_VERSION: 1.22.1
    environment:
      - TZ=JST-9
    ports:
      - 80:80
      - 3000:3000
    volumes:
      # ソースコードとdevcontainerを一緒に管理する場合は明示的にマウント先を指定
      - ..:/home/vscode/develop:cached
      - ~/.ssh:/home/vscode/.ssh
      - .extensions:$HOME_DIR/.vscode-server/extensions
      - .go:/home/vscode/go
    command: sleep infinity
