host: localhost:8080
info:
  contact: {}
  description: ユーザー管理サービスAPIの昨日
  title: ユーザー管理サービスAPI
  version: 0.1.0
paths:
  /v1/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 死活監視用
      tags:
      - healthcheck
  /v1/users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: ユーザー一覧取得
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: ユーザー情報の編集
      tags:
      - users
  /v1/users/:id:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: ユーザー情報の削除
      tags:
      - users
    get:
      consumes:
      - application/json
      parameters:
      - description: ユーザーID
        in: path
        name: request
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
      summary: ユーザーの詳細情報を取得
      tags:
      - users
swagger: "2.0"
